import os
import rtconfig
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
''')
    
# add gpio driver code
if GetDepend('BSP_USING_GPIO'):
    src = src + ['drv_gpio.c']
    
# add uart driver code
if GetDepend('BSP_USING_UART'):
    src = src + ['drv_uart.c']

# add i2c driver code
if GetDepend('BSP_USING_I2C'):
    src = src + ['drv_i2c.c']
    
# add spi driver code
if GetDepend('BSP_USING_SPI'):
    src = src + ['drv_spi.c']


path =  [cwd]

if rtconfig.CROSS_TOOL == 'gcc':
    src += [cwd + '/../libraries/Startup/IAR/startup_ht6x3x.s']
elif rtconfig.CROSS_TOOL == 'keil':
    src += [cwd + '/../libraries/Startup/IAR/startup_ht6x3x.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src += [cwd + '/../libraries/Startup/IAR/startup_ht6x3x.s']

# HT6x3x || HT6x2x || HT6x1x
# HT501x || HT502x
# You can select chips from the list above
CPPDEFINES = ['HT6x3x']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)
Return('group')
